// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry-edge.proto

/*
Package telemetry_edge is a generated protocol buffer package.

It is generated from these files:
	telemetry-edge.proto

It has these top-level messages:
	EnvoySummary
	Agent
	EnvoyInstruction
	EnvoyInstructionInstall
	EnvoyInstructionConfigure
	ConfigurationOp
	EnvoyInstructionRefresh
	KeepAliveRequest
	KeepAliveResponse
	LogEvent
	PostLogEventResponse
*/
package telemetry_edge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentType int32

const (
	AgentType_TELEGRAF AgentType = 0
	AgentType_FILEBEAT AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "TELEGRAF",
	1: "FILEBEAT",
}
var AgentType_value = map[string]int32{
	"TELEGRAF": 0,
	"FILEBEAT": 1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}
func (AgentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConfigurationOp_Type int32

const (
	ConfigurationOp_MODIFY ConfigurationOp_Type = 0
	ConfigurationOp_REMOVE ConfigurationOp_Type = 1
)

var ConfigurationOp_Type_name = map[int32]string{
	0: "MODIFY",
	1: "REMOVE",
}
var ConfigurationOp_Type_value = map[string]int32{
	"MODIFY": 0,
	"REMOVE": 1,
}

func (x ConfigurationOp_Type) String() string {
	return proto.EnumName(ConfigurationOp_Type_name, int32(x))
}
func (ConfigurationOp_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type EnvoySummary struct {
	Version         string            `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	InstanceId      string            `protobuf:"bytes,2,opt,name=instanceId" json:"instanceId,omitempty"`
	SupportedAgents []AgentType       `protobuf:"varint,3,rep,packed,name=supportedAgents,enum=AgentType" json:"supportedAgents,omitempty"`
	Labels          map[string]string `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *EnvoySummary) Reset()                    { *m = EnvoySummary{} }
func (m *EnvoySummary) String() string            { return proto.CompactTextString(m) }
func (*EnvoySummary) ProtoMessage()               {}
func (*EnvoySummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EnvoySummary) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *EnvoySummary) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *EnvoySummary) GetSupportedAgents() []AgentType {
	if m != nil {
		return m.SupportedAgents
	}
	return nil
}

func (m *EnvoySummary) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Agent struct {
	Type    AgentType `protobuf:"varint,1,opt,name=type,enum=AgentType" json:"type,omitempty"`
	Version string    `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Agent) Reset()                    { *m = Agent{} }
func (m *Agent) String() string            { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()               {}
func (*Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_TELEGRAF
}

func (m *Agent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type EnvoyInstruction struct {
	// Types that are valid to be assigned to Details:
	//	*EnvoyInstruction_Install
	//	*EnvoyInstruction_Configure
	//	*EnvoyInstruction_Refresh
	Details isEnvoyInstruction_Details `protobuf_oneof:"details"`
}

func (m *EnvoyInstruction) Reset()                    { *m = EnvoyInstruction{} }
func (m *EnvoyInstruction) String() string            { return proto.CompactTextString(m) }
func (*EnvoyInstruction) ProtoMessage()               {}
func (*EnvoyInstruction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isEnvoyInstruction_Details interface {
	isEnvoyInstruction_Details()
}

type EnvoyInstruction_Install struct {
	Install *EnvoyInstructionInstall `protobuf:"bytes,1,opt,name=install,oneof"`
}
type EnvoyInstruction_Configure struct {
	Configure *EnvoyInstructionConfigure `protobuf:"bytes,2,opt,name=configure,oneof"`
}
type EnvoyInstruction_Refresh struct {
	Refresh *EnvoyInstructionRefresh `protobuf:"bytes,3,opt,name=refresh,oneof"`
}

func (*EnvoyInstruction_Install) isEnvoyInstruction_Details()   {}
func (*EnvoyInstruction_Configure) isEnvoyInstruction_Details() {}
func (*EnvoyInstruction_Refresh) isEnvoyInstruction_Details()   {}

func (m *EnvoyInstruction) GetDetails() isEnvoyInstruction_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *EnvoyInstruction) GetInstall() *EnvoyInstructionInstall {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Install); ok {
		return x.Install
	}
	return nil
}

func (m *EnvoyInstruction) GetConfigure() *EnvoyInstructionConfigure {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Configure); ok {
		return x.Configure
	}
	return nil
}

func (m *EnvoyInstruction) GetRefresh() *EnvoyInstructionRefresh {
	if x, ok := m.GetDetails().(*EnvoyInstruction_Refresh); ok {
		return x.Refresh
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EnvoyInstruction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EnvoyInstruction_OneofMarshaler, _EnvoyInstruction_OneofUnmarshaler, _EnvoyInstruction_OneofSizer, []interface{}{
		(*EnvoyInstruction_Install)(nil),
		(*EnvoyInstruction_Configure)(nil),
		(*EnvoyInstruction_Refresh)(nil),
	}
}

func _EnvoyInstruction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EnvoyInstruction)
	// details
	switch x := m.Details.(type) {
	case *EnvoyInstruction_Install:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Install); err != nil {
			return err
		}
	case *EnvoyInstruction_Configure:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Configure); err != nil {
			return err
		}
	case *EnvoyInstruction_Refresh:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Refresh); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EnvoyInstruction.Details has unexpected type %T", x)
	}
	return nil
}

func _EnvoyInstruction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EnvoyInstruction)
	switch tag {
	case 1: // details.install
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnvoyInstructionInstall)
		err := b.DecodeMessage(msg)
		m.Details = &EnvoyInstruction_Install{msg}
		return true, err
	case 2: // details.configure
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnvoyInstructionConfigure)
		err := b.DecodeMessage(msg)
		m.Details = &EnvoyInstruction_Configure{msg}
		return true, err
	case 3: // details.refresh
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnvoyInstructionRefresh)
		err := b.DecodeMessage(msg)
		m.Details = &EnvoyInstruction_Refresh{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EnvoyInstruction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EnvoyInstruction)
	// details
	switch x := m.Details.(type) {
	case *EnvoyInstruction_Install:
		s := proto.Size(x.Install)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EnvoyInstruction_Configure:
		s := proto.Size(x.Configure)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EnvoyInstruction_Refresh:
		s := proto.Size(x.Refresh)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EnvoyInstructionInstall struct {
	Agent    *Agent `protobuf:"bytes,1,opt,name=agent" json:"agent,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Checksum string `protobuf:"bytes,3,opt,name=checksum" json:"checksum,omitempty"`
}

func (m *EnvoyInstructionInstall) Reset()                    { *m = EnvoyInstructionInstall{} }
func (m *EnvoyInstructionInstall) String() string            { return proto.CompactTextString(m) }
func (*EnvoyInstructionInstall) ProtoMessage()               {}
func (*EnvoyInstructionInstall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnvoyInstructionInstall) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *EnvoyInstructionInstall) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EnvoyInstructionInstall) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

type EnvoyInstructionConfigure struct {
	AgentType  AgentType          `protobuf:"varint,1,opt,name=agentType,enum=AgentType" json:"agentType,omitempty"`
	Operations []*ConfigurationOp `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
}

func (m *EnvoyInstructionConfigure) Reset()                    { *m = EnvoyInstructionConfigure{} }
func (m *EnvoyInstructionConfigure) String() string            { return proto.CompactTextString(m) }
func (*EnvoyInstructionConfigure) ProtoMessage()               {}
func (*EnvoyInstructionConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *EnvoyInstructionConfigure) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_TELEGRAF
}

func (m *EnvoyInstructionConfigure) GetOperations() []*ConfigurationOp {
	if m != nil {
		return m.Operations
	}
	return nil
}

type ConfigurationOp struct {
	Id       string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Revision string               `protobuf:"bytes,2,opt,name=revision" json:"revision,omitempty"`
	Type     ConfigurationOp_Type `protobuf:"varint,3,opt,name=type,enum=ConfigurationOp_Type" json:"type,omitempty"`
	Content  string               `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *ConfigurationOp) Reset()                    { *m = ConfigurationOp{} }
func (m *ConfigurationOp) String() string            { return proto.CompactTextString(m) }
func (*ConfigurationOp) ProtoMessage()               {}
func (*ConfigurationOp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConfigurationOp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfigurationOp) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ConfigurationOp) GetType() ConfigurationOp_Type {
	if m != nil {
		return m.Type
	}
	return ConfigurationOp_MODIFY
}

func (m *ConfigurationOp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// mainly used to test the ambassador->envoy liveness of the channel, but could eventually
// contain the full set of instructions of ensure consistency
type EnvoyInstructionRefresh struct {
}

func (m *EnvoyInstructionRefresh) Reset()                    { *m = EnvoyInstructionRefresh{} }
func (m *EnvoyInstructionRefresh) String() string            { return proto.CompactTextString(m) }
func (*EnvoyInstructionRefresh) ProtoMessage()               {}
func (*EnvoyInstructionRefresh) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type KeepAliveRequest struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instanceId" json:"instanceId,omitempty"`
}

func (m *KeepAliveRequest) Reset()                    { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()               {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *KeepAliveRequest) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type KeepAliveResponse struct {
}

func (m *KeepAliveResponse) Reset()                    { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string            { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()               {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LogEvent struct {
	InstanceId  string    `protobuf:"bytes,1,opt,name=instanceId" json:"instanceId,omitempty"`
	AgentType   AgentType `protobuf:"varint,2,opt,name=agentType,enum=AgentType" json:"agentType,omitempty"`
	JsonContent string    `protobuf:"bytes,3,opt,name=jsonContent" json:"jsonContent,omitempty"`
}

func (m *LogEvent) Reset()                    { *m = LogEvent{} }
func (m *LogEvent) String() string            { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()               {}
func (*LogEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LogEvent) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *LogEvent) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_TELEGRAF
}

func (m *LogEvent) GetJsonContent() string {
	if m != nil {
		return m.JsonContent
	}
	return ""
}

type PostLogEventResponse struct {
}

func (m *PostLogEventResponse) Reset()                    { *m = PostLogEventResponse{} }
func (m *PostLogEventResponse) String() string            { return proto.CompactTextString(m) }
func (*PostLogEventResponse) ProtoMessage()               {}
func (*PostLogEventResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*EnvoySummary)(nil), "EnvoySummary")
	proto.RegisterType((*Agent)(nil), "Agent")
	proto.RegisterType((*EnvoyInstruction)(nil), "EnvoyInstruction")
	proto.RegisterType((*EnvoyInstructionInstall)(nil), "EnvoyInstructionInstall")
	proto.RegisterType((*EnvoyInstructionConfigure)(nil), "EnvoyInstructionConfigure")
	proto.RegisterType((*ConfigurationOp)(nil), "ConfigurationOp")
	proto.RegisterType((*EnvoyInstructionRefresh)(nil), "EnvoyInstructionRefresh")
	proto.RegisterType((*KeepAliveRequest)(nil), "KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "KeepAliveResponse")
	proto.RegisterType((*LogEvent)(nil), "LogEvent")
	proto.RegisterType((*PostLogEventResponse)(nil), "PostLogEventResponse")
	proto.RegisterEnum("AgentType", AgentType_name, AgentType_value)
	proto.RegisterEnum("ConfigurationOp_Type", ConfigurationOp_Type_name, ConfigurationOp_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TelemetryAmbassador service

type TelemetryAmbassadorClient interface {
	AttachEnvoy(ctx context.Context, in *EnvoySummary, opts ...grpc.CallOption) (TelemetryAmbassador_AttachEnvoyClient, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	PostLogEvent(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*PostLogEventResponse, error)
}

type telemetryAmbassadorClient struct {
	cc *grpc.ClientConn
}

func NewTelemetryAmbassadorClient(cc *grpc.ClientConn) TelemetryAmbassadorClient {
	return &telemetryAmbassadorClient{cc}
}

func (c *telemetryAmbassadorClient) AttachEnvoy(ctx context.Context, in *EnvoySummary, opts ...grpc.CallOption) (TelemetryAmbassador_AttachEnvoyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TelemetryAmbassador_serviceDesc.Streams[0], c.cc, "/TelemetryAmbassador/AttachEnvoy", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryAmbassadorAttachEnvoyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TelemetryAmbassador_AttachEnvoyClient interface {
	Recv() (*EnvoyInstruction, error)
	grpc.ClientStream
}

type telemetryAmbassadorAttachEnvoyClient struct {
	grpc.ClientStream
}

func (x *telemetryAmbassadorAttachEnvoyClient) Recv() (*EnvoyInstruction, error) {
	m := new(EnvoyInstruction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *telemetryAmbassadorClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := grpc.Invoke(ctx, "/TelemetryAmbassador/KeepAlive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryAmbassadorClient) PostLogEvent(ctx context.Context, in *LogEvent, opts ...grpc.CallOption) (*PostLogEventResponse, error) {
	out := new(PostLogEventResponse)
	err := grpc.Invoke(ctx, "/TelemetryAmbassador/PostLogEvent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TelemetryAmbassador service

type TelemetryAmbassadorServer interface {
	AttachEnvoy(*EnvoySummary, TelemetryAmbassador_AttachEnvoyServer) error
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	PostLogEvent(context.Context, *LogEvent) (*PostLogEventResponse, error)
}

func RegisterTelemetryAmbassadorServer(s *grpc.Server, srv TelemetryAmbassadorServer) {
	s.RegisterService(&_TelemetryAmbassador_serviceDesc, srv)
}

func _TelemetryAmbassador_AttachEnvoy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EnvoySummary)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryAmbassadorServer).AttachEnvoy(m, &telemetryAmbassadorAttachEnvoyServer{stream})
}

type TelemetryAmbassador_AttachEnvoyServer interface {
	Send(*EnvoyInstruction) error
	grpc.ServerStream
}

type telemetryAmbassadorAttachEnvoyServer struct {
	grpc.ServerStream
}

func (x *telemetryAmbassadorAttachEnvoyServer) Send(m *EnvoyInstruction) error {
	return x.ServerStream.SendMsg(m)
}

func _TelemetryAmbassador_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryAmbassador_PostLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryAmbassadorServer).PostLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TelemetryAmbassador/PostLogEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryAmbassadorServer).PostLogEvent(ctx, req.(*LogEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelemetryAmbassador_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TelemetryAmbassador",
	HandlerType: (*TelemetryAmbassadorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _TelemetryAmbassador_KeepAlive_Handler,
		},
		{
			MethodName: "PostLogEvent",
			Handler:    _TelemetryAmbassador_PostLogEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachEnvoy",
			Handler:       _TelemetryAmbassador_AttachEnvoy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "telemetry-edge.proto",
}

func init() { proto.RegisterFile("telemetry-edge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0x8e, 0x93, 0x10, 0xf0, 0x84, 0x03, 0x66, 0x81, 0x73, 0x4c, 0xce, 0x39, 0x28, 0xda, 0x9b,
	0xa6, 0x95, 0xba, 0xa2, 0x81, 0x8b, 0x96, 0xbb, 0xd0, 0x9a, 0x12, 0x35, 0x88, 0xca, 0x8d, 0x2a,
	0xf5, 0xd2, 0x38, 0x43, 0x70, 0x71, 0x6c, 0x77, 0x77, 0xed, 0x2a, 0xaf, 0xd3, 0x67, 0xe8, 0x2b,
	0xf4, 0x6d, 0xfa, 0x10, 0x95, 0xd7, 0x76, 0x70, 0x1c, 0xe0, 0x6e, 0xe7, 0x67, 0x67, 0xbe, 0xf9,
	0xbe, 0xd9, 0x85, 0x3d, 0x89, 0x3e, 0xce, 0x50, 0xf2, 0xf9, 0x4b, 0x9c, 0x4c, 0x91, 0x45, 0x3c,
	0x94, 0x21, 0xfd, 0xad, 0xc1, 0xa6, 0x15, 0x24, 0xe1, 0xfc, 0x53, 0x3c, 0x9b, 0x39, 0x7c, 0x4e,
	0x4c, 0x58, 0x4f, 0x90, 0x0b, 0x2f, 0x0c, 0x4c, 0xad, 0xab, 0xf5, 0x74, 0xbb, 0x30, 0xc9, 0x21,
	0x80, 0x17, 0x08, 0xe9, 0x04, 0x2e, 0x0e, 0x27, 0x66, 0x5d, 0x05, 0x4b, 0x1e, 0x72, 0x02, 0xdb,
	0x22, 0x8e, 0xa2, 0x90, 0x4b, 0x9c, 0x0c, 0xa6, 0x18, 0x48, 0x61, 0x36, 0xba, 0x8d, 0xde, 0x56,
	0x1f, 0x98, 0x32, 0xc7, 0xf3, 0x08, 0xed, 0x6a, 0x0a, 0x79, 0x05, 0x2d, 0xdf, 0xb9, 0x46, 0x5f,
	0x98, 0xcd, 0x6e, 0xa3, 0xd7, 0xee, 0x1f, 0xb0, 0x32, 0x1c, 0x36, 0x52, 0x31, 0x2b, 0x90, 0x7c,
	0x6e, 0xe7, 0x89, 0x9d, 0x37, 0xd0, 0x2e, 0xb9, 0x89, 0x01, 0x8d, 0x3b, 0x9c, 0xe7, 0x68, 0xd3,
	0x23, 0xd9, 0x83, 0xb5, 0xc4, 0xf1, 0x63, 0xcc, 0x41, 0x66, 0xc6, 0x69, 0xfd, 0xb5, 0x46, 0x07,
	0xb0, 0xa6, 0xfa, 0x92, 0x43, 0x68, 0xca, 0x79, 0x84, 0xea, 0xd6, 0x32, 0x42, 0xe5, 0x2f, 0xd3,
	0x50, 0x5f, 0xa2, 0x81, 0xfe, 0xd2, 0xc0, 0x50, 0x10, 0x87, 0x81, 0x90, 0x3c, 0x76, 0x65, 0xca,
	0xcd, 0x09, 0xac, 0x2b, 0x26, 0x7c, 0x5f, 0x55, 0x6c, 0xf7, 0x4d, 0x56, 0xcd, 0x19, 0x66, 0xf1,
	0x8b, 0x9a, 0x5d, 0xa4, 0x92, 0x53, 0xd0, 0xdd, 0x30, 0xb8, 0xf1, 0xa6, 0x31, 0xcf, 0xb0, 0xb6,
	0xfb, 0x9d, 0x95, 0x7b, 0x6f, 0x8b, 0x8c, 0x8b, 0x9a, 0x7d, 0x9f, 0x9e, 0x76, 0xe4, 0x78, 0xc3,
	0x51, 0xdc, 0x9a, 0x8d, 0x47, 0x3a, 0xda, 0x59, 0x3c, 0xed, 0x98, 0xa7, 0x9e, 0xe9, 0xb0, 0x3e,
	0x41, 0xe9, 0x78, 0xbe, 0xa0, 0x08, 0xff, 0x3c, 0x02, 0x91, 0xfc, 0x07, 0x6b, 0x4e, 0xca, 0x47,
	0x3e, 0x4b, 0x2b, 0x63, 0xc7, 0xce, 0x9c, 0x29, 0xdf, 0x31, 0xf7, 0x73, 0x5a, 0xd2, 0x23, 0xe9,
	0xc0, 0x86, 0x7b, 0x8b, 0xee, 0x9d, 0x88, 0x67, 0x0a, 0x8c, 0x6e, 0x2f, 0x6c, 0xfa, 0x1d, 0x0e,
	0x1e, 0x9d, 0x88, 0xf4, 0x40, 0x77, 0x0a, 0xe2, 0x1f, 0x90, 0xe2, 0x3e, 0x48, 0x8e, 0x00, 0xc2,
	0x08, 0xb9, 0x93, 0xde, 0x17, 0x66, 0x5d, 0xad, 0x8a, 0xc1, 0x8a, 0x4a, 0xca, 0x7d, 0x15, 0xd9,
	0xa5, 0x1c, 0xfa, 0x43, 0x83, 0xed, 0x4a, 0x9c, 0x6c, 0x41, 0xdd, 0x9b, 0xe4, 0x9b, 0x52, 0xf7,
	0x26, 0x29, 0x70, 0x8e, 0x89, 0x57, 0x92, 0x79, 0x61, 0x93, 0xe7, 0xf9, 0x86, 0x34, 0x14, 0xac,
	0xfd, 0x6a, 0x2f, 0xb6, 0xbc, 0x2c, 0x6e, 0x18, 0xc8, 0x94, 0xb1, 0x66, 0xb6, 0x2c, 0xb9, 0x49,
	0x0f, 0xa1, 0xa9, 0xe0, 0x03, 0xb4, 0x2e, 0xaf, 0xde, 0x0d, 0xcf, 0xbf, 0x18, 0xb5, 0xf4, 0x6c,
	0x5b, 0x97, 0x57, 0x9f, 0x2d, 0x43, 0xa3, 0x07, 0xab, 0x22, 0xe4, 0xaa, 0xd1, 0x3e, 0x18, 0x1f,
	0x10, 0xa3, 0x81, 0xef, 0x25, 0x68, 0xe3, 0xb7, 0x18, 0x85, 0xac, 0x3c, 0x41, 0xad, 0xfa, 0x04,
	0xe9, 0x2e, 0xec, 0x94, 0xee, 0x88, 0x28, 0x0c, 0x04, 0xd2, 0x04, 0x36, 0x46, 0xe1, 0xd4, 0x4a,
	0xb2, 0xb5, 0x7f, 0xb2, 0xc0, 0xb2, 0x20, 0xf5, 0xa7, 0x04, 0xe9, 0x42, 0xfb, 0xab, 0x50, 0x5a,
	0xaa, 0xb9, 0x33, 0xd9, 0xcb, 0x2e, 0xfa, 0x37, 0xec, 0x7d, 0x0c, 0x85, 0x2c, 0x7a, 0x17, 0x78,
	0x5e, 0x3c, 0x03, 0x7d, 0x51, 0x91, 0x6c, 0xc2, 0xc6, 0xd8, 0x1a, 0x59, 0xef, 0xed, 0xc1, 0xb9,
	0x51, 0x4b, 0xad, 0xf3, 0xe1, 0xc8, 0x3a, 0xb3, 0x06, 0x63, 0x43, 0xeb, 0xff, 0xd4, 0x60, 0x77,
	0x5c, 0x7c, 0x5a, 0x83, 0xd9, 0xb5, 0x23, 0x84, 0x33, 0x09, 0x39, 0x39, 0x86, 0xf6, 0x40, 0x4a,
	0xc7, 0xbd, 0x55, 0xd4, 0x91, 0xbf, 0x96, 0x7e, 0x8c, 0xce, 0xce, 0xca, 0x3b, 0xa0, 0xb5, 0x23,
	0x8d, 0x9c, 0x80, 0xbe, 0xa0, 0x86, 0xec, 0xb0, 0x2a, 0xb5, 0x1d, 0xc2, 0x56, 0x99, 0xab, 0x91,
	0x3e, 0x6c, 0x96, 0x67, 0x20, 0x3a, 0x2b, 0x8e, 0x9d, 0x7d, 0xf6, 0xd0, 0x74, 0xb4, 0x76, 0xf6,
	0x3f, 0xfc, 0xeb, 0x86, 0x33, 0xc6, 0x1d, 0xf7, 0x4e, 0x44, 0x8e, 0x8b, 0x8c, 0xcf, 0x3c, 0x8f,
	0x09, 0xe4, 0x89, 0xe7, 0xa2, 0xb8, 0x6e, 0xa9, 0x8f, 0xf7, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x8b, 0xee, 0x44, 0x90, 0x05, 0x00, 0x00,
}
