project_name: telemetry-envoy
before:
  hooks:
  - go generate ./telemetry_edge
  - go generate ./...
builds:
- binary: telemetry-envoy
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ignore:
  - goos: darwin
    goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^test:'
    - '^build:'
