project_name: telemetry-envoy
before:
  hooks:
  - go generate ./telemetry_edge
  - go generate ./...
builds:
- binary: telemetry-envoy
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  ignore:
  - goos: darwin
    goarch: 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  vendor: Rackspace
  homepage: https://www.rackspace.com/
  description: Monitoring application which submits system metrics for further analysis.
  license: Apache 2.0
  formats:
    - deb
    - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^test:'
    - '^build:'
